### ISSUE TITLE
EqualizerServer does not compile on ubuntu 14.04 (possibly others as well)

### ISSUE THREAD

**Issue by RubenGarcia** [caprica/vlcj#426]
When running make (after fixing the issues in bugs 
https://github.com/Eyescale/Equalizer/issues/513
and
https://github.com/Eyescale/Lunchbox/issues/227,
the build fails in resources.cpp

[ 58%] Building CXX object eq/server/CMakeFiles/EqualizerServer.dir/config/resources.cpp.o
/home/rgarcia/lrz/equalizer/Equalizer/eq/server/config/resources.cpp: In static member function ‘static bool eq::server::config::Resources::discover(eq::server::ServerPtr, eq::server::Config*, const string&, const eq::fabric::ConfigParams&)’:
/home/rgarcia/lrz/equalizer/Equalizer/eq/server/config/resources.cpp:328:34: error: ‘FLAG_VNC’ is not a member of ‘hwsd::GPUInfo’
                                  hwsd::GPUInfo::FLAG_VNC )) ==
                                  ^
make[2]: *** [eq/server/CMakeFiles/EqualizerServer.dir/config/resources.cpp.o] Error 1
make[1]: *** [eq/server/CMakeFiles/EqualizerServer.dir/all] Error 2

**Comment by RubenGarcia** [comment]
After removal of Equalizer and re-clone, the problem persists.

**Comment by caprica** [comment]
What has this got to do with my project?

**Comment by RubenGarcia** [comment]
Sorry, I must have pressed on the wrong thing. This is indeed the wrong project. Closing.
